#!/usr/bin/env python3
"""
Artificial Bestiary — Haiku 4.5 Cross-Architecture Extension
============================================================

Runs the 800-trial retest stimulus set against Claude Haiku 4.5, with all
parameters matched to the original Sonnet 4.6 retest in this project so the
two datasets are directly comparable.

Stimulus set (mirrors the v3 retest):
  8 words × 10 conditions × 10 trials = 800 trials

Words:
  4 from Chesterton's original pilot:    borthorpunius, halthibinny,
                                         purtaneolotomous, wresanthamulf
  4 generated by analyst (Opus 4.7):     flembrast, kovashent, plindorf, trolnique

Conditions (identical to first study):
  neutral
  real / imaginary / type_of  ×  animal / object / idea

Parameters held constant with the Sonnet retest:
  temperature = 1.0
  max_tokens  = 400
  no system prompt, no tools, no extended thinking

Usage:
    export ANTHROPIC_API_KEY=sk-...

    # Smoke test (no API):
    python haiku_cross_arch.py run --dry-run

    # Smoke test (real API, 6 trials):
    python haiku_cross_arch.py run --limit 6 --out Results/haiku_smoke.jsonl

    # Full run (~12-15 min, ~$2-4):
    python haiku_cross_arch.py run --out Results/haiku_results.jsonl

    # Resume after interruption:
    python haiku_cross_arch.py run --out Results/haiku_results.jsonl --resume

    # Pinned model (reproducibility):
    python haiku_cross_arch.py run --out Results/haiku_results.jsonl \\
        --model claude-haiku-4-5-20251001

    # Quick analyze:
    python haiku_cross_arch.py analyze Results/haiku_results.jsonl \\
        --outdir analysis/haiku/
"""

from __future__ import annotations

import argparse
import csv
import json
import os
import random
import threading
import time
from collections import defaultdict
from concurrent.futures import ThreadPoolExecutor, as_completed
from itertools import product
from pathlib import Path


# ---------------------------------------------------------------------------
# Study parameters — held constant with the Sonnet retest where possible
# ---------------------------------------------------------------------------

DEFAULT_MODEL  = "claude-haiku-4-5"          # latest alias
PINNED_MODEL   = "claude-haiku-4-5-20251001" # pinned snapshot

MAX_TOKENS         = 400      # matches v3 Sonnet runner
TEMPERATURE        = 1.0      # matches v3 Sonnet runner
MAX_WORKERS        = 4        # matches v3 Sonnet runner
MIN_INTERVAL_SEC   = 1.5      # matches v3 Sonnet runner
MAX_RETRIES        = 5
BACKOFF_BASE       = 3.0
PROGRESS_INTERVAL  = 50

TRIALS_PER_CELL    = 10       # matches v3 retest (NOT the 20 of the original pilot)
SEED               = 20260501 # different from pilot's 20260429 — separate trial draw

# Eight-word retest set (4 original + 4 analyst-generated)
WORDS_ORIGINAL = [
    "borthorpunius",
    "halthibinny",
    "purtaneolotomous",
    "wresanthamulf",
]
WORDS_ANALYST = [
    "flembrast",
    "kovashent",
    "plindorf",
    "trolnique",
]
WORDS = WORDS_ORIGINAL + WORDS_ANALYST

REALITY_STATUSES = ["real", "imaginary", "type of"]
CATEGORIES       = ["animal", "object", "idea"]


def _make_conditions() -> dict[str, dict]:
    """Build the 10 conditions: neutral + 3 reality × 3 category."""
    conds = {}
    conds["neutral"] = {
        "label": "neutral",
        "reality": None,
        "category": None,
        "template": "Describe a {word}.",
    }
    for reality, category in product(REALITY_STATUSES, CATEGORIES):
        key = f"{reality.replace(' ', '_')}_{category}"
        article = "an" if reality[0] in "aeiou" else "a"
        conds[key] = {
            "label": key,
            "reality": reality,
            "category": category,
            "template": f"Describe a {{word}}. It is {article} {reality} {category}.",
        }
    return conds


CONDITIONS = _make_conditions()


# ---------------------------------------------------------------------------
# Trial construction
# ---------------------------------------------------------------------------

def build_trials(trials_per_cell: int = TRIALS_PER_CELL, seed: int = SEED) -> list[dict]:
    """Build the (8 × 10 × trials_per_cell) trial list, shuffled."""
    trials = []
    idx = 0
    for word in WORDS:
        for cond_key, cond in CONDITIONS.items():
            prompt = cond["template"].format(word=word)
            word_set = "original" if word in WORDS_ORIGINAL else "analyst"
            for n in range(trials_per_cell):
                trials.append({
                    "trial_id": f"{idx:05d}",
                    "word": word,
                    "word_set": word_set,
                    "condition": cond_key,
                    "reality": cond["reality"],
                    "category": cond["category"],
                    "trial_n": n,
                    "prompt": prompt,
                })
                idx += 1
    rng = random.Random(seed)
    rng.shuffle(trials)
    return trials


# ---------------------------------------------------------------------------
# Runner
# ---------------------------------------------------------------------------

class Throttle:
    def __init__(self, min_interval: float):
        self.min_interval = min_interval
        self.last = 0.0
        self.lock = threading.Lock()

    def wait(self) -> None:
        with self.lock:
            now = time.time()
            gap = self.min_interval - (now - self.last)
            if gap > 0:
                time.sleep(gap)
            self.last = time.time()


def run_one(client, model: str, trial: dict, throttle: Throttle) -> dict:
    """Run a single trial. Mirrors v3's run_one exactly except for model arg."""
    import anthropic
    last_err = None
    for attempt in range(MAX_RETRIES):
        try:
            throttle.wait()
            t0 = time.time()
            resp = client.messages.create(
                model=model,
                max_tokens=MAX_TOKENS,
                temperature=TEMPERATURE,
                messages=[{"role": "user", "content": trial["prompt"]}],
            )
            text = "".join(
                b.text for b in resp.content if getattr(b, "type", None) == "text"
            )
            return {
                **trial,
                "model": model,
                "response": text,
                "stop_reason": resp.stop_reason,
                "input_tokens": resp.usage.input_tokens,
                "output_tokens": resp.usage.output_tokens,
                "latency_sec": round(time.time() - t0, 3),
                "attempts": attempt + 1,
                "error": None,
            }
        except (anthropic.APIStatusError, anthropic.APIConnectionError) as e:
            last_err = f"{type(e).__name__}: {e}"
            time.sleep(BACKOFF_BASE ** attempt + random.uniform(0, 1))
        except Exception as e:
            last_err = f"{type(e).__name__}: {e}"
            break
    return {
        **trial,
        "model": model,
        "response": None,
        "stop_reason": None,
        "input_tokens": None,
        "output_tokens": None,
        "latency_sec": None,
        "attempts": MAX_RETRIES,
        "error": last_err,
    }


def load_done(path: Path) -> set[str]:
    """Load trial_ids already completed (used for --resume)."""
    if not path.exists():
        return set()
    done = set()
    with path.open() as f:
        for line in f:
            try:
                r = json.loads(line)
                if r.get("response") is not None and not r.get("error"):
                    done.add(r["trial_id"])
            except json.JSONDecodeError:
                continue
    return done


def cmd_run(args: argparse.Namespace) -> None:
    trials = build_trials(args.trials_per_cell)
    if args.limit:
        trials = trials[: args.limit]

    total = len(trials)
    n_words = len(WORDS)
    n_conds = len(CONDITIONS)
    full_total = n_words * n_conds * args.trials_per_cell

    print(
        f"Words: {n_words} (4 original + 4 analyst) | "
        f"Conditions: {n_conds} | Trials/cell: {args.trials_per_cell} | "
        f"Total planned: {full_total}"
    )
    print(f"Running: {total} trials")
    print(
        f"Model: {args.model} | Temp: {TEMPERATURE} | Max tokens: {MAX_TOKENS} | "
        f"Throttle: {MAX_WORKERS} workers, {MIN_INTERVAL_SEC}s min interval"
    )
    eta_sec = total * MIN_INTERVAL_SEC / MAX_WORKERS
    print(f"Estimated runtime: ~{eta_sec / 60:.0f} min")
    # Cost estimate: Haiku 4.5 = $1/M input, $5/M output
    # Each trial roughly: 25 input tokens, 200 output tokens (Sonnet retest avg)
    est_cost = total * (25/1_000_000 * 1.0 + 200/1_000_000 * 5.0)
    print(f"Estimated API cost: ~${est_cost:.2f}")

    if args.dry_run:
        print("\nSample prompts (one per condition):")
        seen = set()
        for t in trials:
            if t["condition"] not in seen:
                seen.add(t["condition"])
                print(f"\n  [{t['condition']}]")
                print(f"  word={t['word']!r} ({t['word_set']})")
                print(f"  prompt={t['prompt']!r}")
            if len(seen) == n_conds:
                break
        return

    if "ANTHROPIC_API_KEY" not in os.environ:
        raise SystemExit("Set ANTHROPIC_API_KEY.")

    out = Path(args.out)
    out.parent.mkdir(parents=True, exist_ok=True)

    if args.resume:
        done = load_done(out)
        trials = [t for t in trials if t["trial_id"] not in done]
        print(f"Resume: skipping {len(done)}, running {len(trials)}.")
        mode = "a"
    else:
        if out.exists() and not args.overwrite:
            raise SystemExit(f"{out} exists. Use --resume or --overwrite.")
        mode = "w"

    if not trials:
        print("Nothing to do.")
        return

    import anthropic
    client = anthropic.Anthropic()
    throttle = Throttle(MIN_INTERVAL_SEC)
    completed = failed = 0
    t0 = time.time()

    with out.open(mode) as f:
        with ThreadPoolExecutor(max_workers=MAX_WORKERS) as pool:
            futs = {
                pool.submit(run_one, client, args.model, t, throttle): t for t in trials
            }
            for fut in as_completed(futs):
                result = fut.result()
                f.write(json.dumps(result) + "\n")
                f.flush()
                completed += 1
                if result["error"]:
                    failed += 1
                if completed % PROGRESS_INTERVAL == 0 or completed == len(trials):
                    elapsed = time.time() - t0
                    rate = completed / elapsed if elapsed else 0
                    eta = (len(trials) - completed) / rate if rate else 0
                    print(
                        f"  [{completed:>5}/{len(trials)}] "
                        f"failed={failed} | {rate:.2f} t/s | ETA {eta:.0f}s"
                    )

    print(f"\nDone. {completed} trials in {time.time() - t0:.1f}s ({failed} failed).")
    print(f"Output: {out.resolve()}")
    if failed:
        print("Re-run with --resume to retry failures.")


# ---------------------------------------------------------------------------
# Analyzer (raw stats only — coding is downstream, hand-coded)
# ---------------------------------------------------------------------------

def cmd_analyze(args: argparse.Namespace) -> None:
    rows = []
    with open(args.input) as f:
        for line in f:
            line = line.strip()
            if line:
                rows.append(json.loads(line))

    outdir = Path(args.outdir)
    outdir.mkdir(parents=True, exist_ok=True)

    total = len(rows)
    errors = sum(1 for r in rows if r.get("error"))
    empty = sum(1 for r in rows if not r.get("error") and not (r.get("response") or "").strip())

    lines = [
        f"Artificial Bestiary — Haiku 4.5 Cross-Architecture Extension",
        f"=============================================================",
        f"Total rows   : {total}",
        f"Errors       : {errors}",
        f"Empty resp.  : {empty}",
        f"Usable       : {total - errors - empty}",
        "",
    ]

    by_cond: dict[str, list[int]] = defaultdict(list)
    by_word: dict[str, list[int]] = defaultdict(list)
    by_cond_word: dict[tuple, list[int]] = defaultdict(list)

    for r in rows:
        if r.get("error") or not (r.get("response") or "").strip():
            continue
        length = len(r["response"].split())
        cond = r.get("condition", "?")
        word = r.get("word", "?")
        by_cond[cond].append(length)
        by_word[word].append(length)
        by_cond_word[(word, cond)].append(length)

    def avg(lst):
        return sum(lst) / len(lst) if lst else 0.0

    lines += ["Response length (words) by condition:", "-" * 50]
    for cond in sorted(by_cond):
        vals = by_cond[cond]
        lines.append(f"  {cond:<30} n={len(vals):>4}  mean={avg(vals):5.1f}w")

    lines += ["", "Response length (words) by word:", "-" * 50]
    for word in sorted(by_word):
        vals = by_word[word]
        lines.append(f"  {word:<25} n={len(vals):>4}  mean={avg(vals):5.1f}w")

    lines += ["", "Cell completion (word × condition):", "-" * 50]
    for word in WORDS:
        lines.append(f"\n  {word}:")
        for cond in CONDITIONS:
            vals = by_cond_word.get((word, cond), [])
            lines.append(f"    {cond:<30} n={len(vals):>3}")

    in_toks  = [r["input_tokens"]  for r in rows if r.get("input_tokens")  is not None]
    out_toks = [r["output_tokens"] for r in rows if r.get("output_tokens") is not None]
    if in_toks:
        # Haiku 4.5 pricing: $1/M input, $5/M output
        cost = sum(in_toks) / 1_000_000 * 1.0 + sum(out_toks) / 1_000_000 * 5.0
        lines += [
            "",
            f"Token usage (usable trials):",
            f"  Input  tokens: total={sum(in_toks):,}  mean={avg(in_toks):.1f}",
            f"  Output tokens: total={sum(out_toks):,}  mean={avg(out_toks):.1f}",
            f"  Estimated cost: ${cost:.4f}",
        ]

    summary = "\n".join(lines)
    print(summary)
    (outdir / "summary.txt").write_text(summary + "\n", encoding="utf-8")

    csv_path = outdir / "responses.csv"
    fieldnames = [
        "trial_id", "word", "word_set", "condition", "reality", "category",
        "trial_n", "prompt", "model", "response", "stop_reason",
        "input_tokens", "output_tokens", "latency_sec", "attempts", "error",
    ]
    with csv_path.open("w", newline="", encoding="utf-8") as f:
        writer = csv.DictWriter(f, fieldnames=fieldnames, extrasaction="ignore")
        writer.writeheader()
        for r in rows:
            writer.writerow(r)

    print(f"\nWrote CSV for hand-coding: {csv_path.resolve()}")
    print(f"Wrote summary: {(outdir / 'summary.txt').resolve()}")


# ---------------------------------------------------------------------------
# CLI
# ---------------------------------------------------------------------------

def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(
        description="Haiku 4.5 cross-architecture extension of the Artificial Bestiary."
    )
    sub = parser.add_subparsers(dest="command", required=True)

    p_run = sub.add_parser("run", help="Run trials against the Anthropic API")
    p_run.add_argument("--out", default="Results/haiku_results.jsonl")
    p_run.add_argument("--model", default=DEFAULT_MODEL,
                       help=f"Model ID (default: {DEFAULT_MODEL}; pinned: {PINNED_MODEL})")
    p_run.add_argument("--dry-run", action="store_true",
                       help="Print sample prompts without calling the API")
    p_run.add_argument("--limit", type=int, default=None,
                       help="Run only the first N trials (for smoke tests)")
    p_run.add_argument("--resume", action="store_true",
                       help="Append to existing output, skipping completed trials")
    p_run.add_argument("--overwrite", action="store_true",
                       help="Overwrite existing output file")
    p_run.add_argument("--trials-per-cell", type=int, default=TRIALS_PER_CELL)

    p_an = sub.add_parser("analyze", help="Summarize raw JSONL output")
    p_an.add_argument("input")
    p_an.add_argument("--outdir", default="analysis/haiku")

    return parser


def main() -> None:
    args = build_parser().parse_args()
    {"run": cmd_run, "analyze": cmd_analyze}[args.command](args)


if __name__ == "__main__":
    main()
